service: productservice
frameworkVersion: '3'

custom:
  productsDbName: cloudX_products
  stocksDbName: cloudX_stocks

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    PRODUCTS_DB_NAME: ${self:custom.productsDbName}
    STOCKS_DB_NAME: ${self:custom.stocksDbName}
    CATALOG_QUEUE:
      Ref: CatalogItemsQueue
    SNS_ARN:
      Ref: CreateProductTopic

  # give access to DBs to everybody
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["Products", "Arn"] }
        - { "Fn::GetAtt": ["Stocks", "Arn"] }

    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - { "Fn::GetAtt": ["CatalogItemsQueue", "Arn"] }

    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: CreateProductTopic


functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          path: /products/{id}
          method: get
  createProduct:
    handler: handler.createProduct
    events:
      - httpApi:
          path: /products
          method: post
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn

resources:
  Resources:
    Products:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productsDbName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Stocks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stocksDbName}
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: CatalogItemsQueue

    CreateProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CreateProductTopic

    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: sirredeemer@gmail.com
        Protocol: email
        TopicArn:
          Ref: CreateProductTopic

